pipeline {
   agent none
   stages {
      stage('Hello') {
         agent {
            label 'agent'
         }
         steps {
            sh 'java -version'
            echo 'Get working directory'
            sh 'pwd'
            sh 'node --version'
         }
      }
      stage('Next') {
         agent {
            docker {
               image 'node:lts-buster-slim'
            }
         }
         steps {
            sh 'node --version'
         }
      }
      stage('Last') {
         agent any
         steps {
            sh 'docker ps -a'
         }
      }
   }
}
